#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 18 14:14:54 2021

@author: benutzer
"""
 edg = cv2.Canny(img, 100, 200)
 plt.imshow(edg)#
 
 
 (t,image_seg)=cv2.threshold(image, 0, 230, cv2.THRESH_BINARY_INV) 
     plt.imshow(image_seg)
     
     
     
     
lines = cv2.HoughLines(img_e, 1, np.pi/90., 60) 
for (rho,theta) in lines[0]:
        x0=rho*np.cos(theta); y0=rho*np.sin(theta)
        x1=np.int(x0­-1000*np.sin(theta) + 0.5) 
        y1=np.int(y0+1000*np.cos(theta) + 0.5)
        x2=np.int(x0+1000*np.sin(theta) + 0.5) 
        y2=np.int(y0­-1000*np.cos(theta) + 0.5) 
        cv2.line(img_rgb, (x1,y1), (x2,y2), (255,0,0))
        
        lines = cv2.HoughLinesP(img_e, 1, np.pi/180, 60, minLineLength=80, maxLineGap=15)
       
        lines = np.squeeze(lines)
        for (x1,y1,x2,y2) in lines:
            cv2.line(img_rgb, (x1,y1), (x2,y2), (255,0,0))
            
            